### ISSUE TITLE
建议调整文字格式

### ISSUE THREAD

**Issue by KZ25T** [Anony-Minor/wcc-ReTong-Homework#1]
相邻两行字中间建议加一行空行，否则 GitHub 渲染会有问题。

以及行内公式两边不建议使用两个 dollar，只需要一个 dollar 符号。

**Comment by Anony-Minor** [comment]
> 相邻两行字中间建议加一行空行，否则 GitHub 渲染会有问题。
> 
> 以及行内公式两边不建议使用两个 dollar，只需要一个 dollar 符号。

抱歉不太会玩GitHub，现在才找到issue在这（

**Comment by KZ25T** [comment]
如果你觉得处理完了一个 issue，那么应该 close 它（

**Comment by Anony-Minor** [comment]
感谢提醒，现在close了
